sudo: false

language: rust

matrix:
  include:
  - rust: stable
    env: PROTOBUF_VERSION=3.1.0
  - rust: beta
    env: PROTOBUF_VERSION=3.1.0
  - rust: nightly
    env: PROTOBUF_VERSION=3.1.0
  - rust: stable
    env: PROTOBUF_VERSION=2.6.1
  - rust: stable
    env: PROTOBUF_VERSION=3.1.0 RUST_PROTOBUF_FEATURES=with-bytes
  - rust: nightly
    env: PROTOBUF_VERSION=3.1.0 RUST_PROTOBUF_FEATURES=with-bytes

before_install:
  - ./install-protobuf.sh
  - PATH=/home/travis/bin:$PATH protoc --version

script:
  - rustc --version
  # Full rebuild with regenerate
  - PATH=/home/travis/bin:$PATH cargo build --manifest-path=protobuf-codegen/Cargo.toml
  # Regenerate only works when proto3
  - PATH=/home/travis/bin:$PATH protobuf/regenerate_if_proto3.sh
  - PATH=/home/travis/bin:$PATH cargo test --all
  # `cargo test --all --features=FFF` doesn't work if there are crates without feature `FFF`
  # hence the explicit list of tests
  - PATH=/home/travis/bin:$PATH protobuf-test/test.sh
  - PATH=/home/travis/bin:$PATH protobuf-codegen-pure-test/test.sh
  - PATH=/home/travis/bin:$PATH protoc/test.sh
  - PATH=/home/travis/bin:$PATH cargo build --all --all-targets

notifications:
  email:
    on_success: never

# vim: set ts=2 sw=2 et:
